// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

/**
 * Item in *Projects → Stack*
 */
export interface ProjectsDocumentDataStackItem {
  /**
   * Technology field in *Projects → Stack*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.stack[].technology
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  technology: prismic.SelectField<
    'Typescript' | 'JavaScript' | 'Next.js' | 'React.js' | 'Go'
  >
}

/**
 * Content for Projects documents
 */
interface ProjectsDocumentData {
  /**
   * Project Name field in *Projects*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.project_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  project_name: prismic.KeyTextField

  /**
   *  Project Link field in *Projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.project_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_link: prismic.LinkField

  /**
   * Repository Link field in *Projects*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.repository_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  repository_link: prismic.LinkField

  /**
   * Is Highlighted field in *Projects*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: projects.is_highlighted
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_highlighted: prismic.BooleanField

  /**
   * Year Started field in *Projects*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.year_started
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  year_started: prismic.NumberField

  /**
   * Year Finished field in *Projects*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.year_finished
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  year_finished: prismic.NumberField

  /**
   * Stack field in *Projects*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.stack[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  stack: prismic.GroupField<Simplify<ProjectsDocumentDataStackItem>>

  /**
   * Banner field in *Projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.banner
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  banner: prismic.ImageField<never>

  /**
   * Content field in *Projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: projects.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField
}

/**
 * Projects document from Prismic
 *
 * - **API ID**: `projects`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProjectsDocumentData>,
    'projects',
    Lang
  >

export type AllDocumentTypes = ProjectsDocument

/**
 * Default variation for Projects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  never
>

/**
 * Slice variation for *Projects*
 */
type ProjectsSliceVariation = ProjectsSliceDefault

/**
 * Projects Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSlice = prismic.SharedSlice<
  'projects',
  ProjectsSliceVariation
>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      ProjectsDocument,
      ProjectsDocumentData,
      ProjectsDocumentDataStackItem,
      AllDocumentTypes,
      ProjectsSlice,
      ProjectsSliceVariation,
      ProjectsSliceDefault,
    }
  }
}
